### ISSUE TITLE
Limited PHP threads?

### ISSUE THREAD

**Issue by JimBrown** [netPhotoGraphics/netPhotoGraphics#1418]
(Tried to login to forum, did not recognize my old creds. Tried to register, got reCaptcha error: [phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 80: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0)

Trying to install a new copy of npg. Works fine on my wamp. Does not work well on the web host. Setup seems to randomly complete only 10 items, the rest are all red X's. (Got through that by exporting/importing options table from wamp to web host).

Image caching appear to only want to do 10 items at a time (in the album/image lists). Anything more than 10 gets broken image thingy. Refreshing page gets next 10 images cached.

I find it strange that the common denominator here is 10. Is there a php setting that limits what appear to be async threads?

Thanks.

**Comment by sbillard** [comment]
I don't understand the PHP Warning--I have checked the server PHP.ini file and allow_url_fopen is set to "on". I will try to register a user and see where that goes. What was your user id on the forum? Maybe I can cause a password reset. Or I can create a new user for you.

The limit if 10 is likely the `Caching concurrency` image option. But why things fail past this limit is more problematic. NPG will try to use the CURL functions to do the these parallel operations if that module is present in PHP. Otherwise it reverts to fetching images from a image url. The value of this is limited by the number of mySQL requests your server allows. NPG fires up  this limit of caching (or setup) requests then waits for them to finish before starting the next group. Sounds like the "next group" is not getting handled properly.

Check to see if your server PHP has the CURL module installed. If it does not, try to get it installed. If it does, maybe there is a flaw in the server implementation. There is a define, `CURL_ENABLED`, in the global-definitions.php file that is gates the use of CURL. You can set it to `FALSE` to revert to the image url fetch mode.

**Comment by sbillard** [comment]
The "allow_url_fopen" issue should be resolved now. Hopefully it does not come back again.

**Comment by JimBrown** [comment]
I just realized I'm trying to install v 2.00.08.06. Let me grab 2.00.14.10 and see what happens. I note my web server host has PHP v8.0 and v8.1 available. Should I go with one of those?

Thanks.

**Comment by sbillard** [comment]
Certainly go to PHP 8.0. PHP 8.1 should also be good. I am running it in my test environment. (My web service provider has not even made PHP 8.0 available yet.) 

But be aware that PHP 8.1 has deprecated passing NULL to a bunch of PHP functions. I believe I have found all the main-line places where that happens in NPG. Unfortunately there is no systematic way to find such calls other than running into them. So you may get some deprecated errors if your site uses a path that my testing does not.

I would certainly appreciate your using PHP 8.1 at least in a test environment. It will help flush out these deprecations.

**Comment by JimBrown** [comment]
Since I'm trying to get my production server going, I'll stick with PHP 7.4 for now. Will test 8.1 on the wamp later.

Installed 2.00.14.10. Still having the same problem. I have a feeling that it might have something to do with "Entry Processes". The plan I'm on with my hosting provider allows for a maximum of 10 "entry processes". Interesting that there is the number 10 again.

I did see on my wamp that the setup routine would show groups of checkmarks. But on the prod server, they pretty much all appeared at the same time, with 10 of them being checkmarks and the rest red X's.

(I have a feeling that the hosting provider has been reducing that limit for a while now in an effort to get me off a very old hosting plan I got before the old hosting provider was bought by the current provider. They keep telling me I'm exceeding resource limits and want me to upgrade my plan. At twice the cost.)

Here's what setup looks like at the moment. (Note that re-running setup will show different X's and checkmarks.)

![image](https://user-images.githubusercontent.com/6067232/183975236-66fed239-b021-44b2-9f1a-5332113204ca.png)

**Comment by sbillard** [comment]
You can try reducing the caching concurrency and see if that helps. 

I presume there is nothing in the nPG debug log. You might also look at the PHP error log on your host for clues. The things that might be involved are: memory limits, the scripts may be running out of memory. MySQL "questions". Presumably MySQL reports the limit on these. If so nPG tries to keep its requests below the limit. But maybe MySQL lies.... Finally a limit on parallel processes. If the server is doing this it really should simply delay starting processes, but maybe it terminates them instead.

As to the grouping of checkmarks, that is likely to be your server's output buffering. nPG tries to flush the buffers after each group, but often servers don't honor the flush and just wait until they have got their buffers filled before delivering the data to your client browser. The variability of what happens also leads one to think it is some kind of resource limit.

Maybe ask your hosting provider what resource limits are being exceeded. That might also be a clue. But in all cases reducing the caching concurrency will reduce the load nPG places on your host.

Finally, for the most part you can ignore the Xes. It would only matter if the plugin/theme has added some initialization requirements. So if over a number of tires each plugin/theme has one successful setup run all will be fine.

**Comment by JimBrown** [comment]
Tried setting caching concurrency to 9 from 13. Only change is that each load of an album index shows 9 new thumbnails instead of 10. If there is more thumbnails they have a broken image link thingy. I also tried setting caching concurrency to 1, the result of which is pretty much the same behaviour (but slower), except that various pages with 20 thumbnails would show 9 or 10 or 11 on their first load, with the rest on the second load, unless it originally showed 9, in which case it would show 18.

However, now setup is completing fully. But, it does not show the progress, it only loads the results page once everything has finished.

According to cPanel metrics, the resource limit I'm hitting is "Entry Processes".

**Comment by sbillard** [comment]
The broken image thingy might be a clue. I don't think that ever happens with the CURL processing, so I think maybe your PHP does not have CURL support. You can check that  with the PHP Info display. (There will be a Development tab for PHPINFO if you have the debug plugin enabled.) If the PHP CURL module is not enabled try to get your provider to enable it. The CURL processing is more efficient than the image fetch alternative.

Not showing progress is because of the server buffering of the output. That is just something we have to live with. 

I suppose that "Entry Processes" would be PHP threads. Image fetching (and CURL requests) would each require a thread. PHP may also have other threads it uses that we have no control over. Since things do seem to work, at least eventually, you can probably just live with the situation (rather than upgrade your service which might not even fix things.)

**Comment by JimBrown** [comment]
CURL does appear to be enabled. This is from phpinfo: 
![image](https://user-images.githubusercontent.com/6067232/184504949-68f301de-ba6f-4034-8ac5-25bb4b638291.png)

Unfortunately, I can't just live with the situation, as the hosting provider does not like my site exceeding their shared hosting resource limits which include Entry Processes, I/O Usage and CPU Usage.

I don't know if this will help, but here's an extract of the access log as I entered the site, then selected one album that had 12 pics in it:
[perthosgallery.rcairgallery.com-ssl.log](https://github.com/netPhotoGraphics/netPhotoGraphics/files/9331943/perthosgallery.rcairgallery.com-ssl.log)

(Note: I'll be out of town until the 24th. Thanks for continuing to look into this).

**Comment by sbillard** [comment]
The only "interesting" thing in the access log is the number of caching requests (the GETs on i.php.) 

It looks like there are actually 13 images fetched from the album. At least that is the number of images initially fetched after the GET of the album. There are also 8 instances of an image being fetched more than once. (4 of these were fetched directly from the cache.) 

You apparently have checked the "Protect image cache" image option. Given your hosting environment I would recommend un-checking the option. Even if the image is already cached running the image processor takes extra processing, I/O, and maybe extra threads.

The other strategy would be to reduce the number of thumbnails on an album page.

**Comment by JimBrown** [comment]
I've upgraded my account at the web host. I should now have enough resources. Closing this one.

Thanks again.
